### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u015a' in position 427: character maps to <undefined>

### ISSUE THREAD

**Issue by lordlouckster** [dlenski/top500#4]

**Comment by dlenski** [comment]
?

You need to provide more information and context about this problem if you want help solving it.

**Comment by lordlouckster** [comment]
Windows 10 Pro 64-bit
Python 3.8.7
pandas 1.2.2
mechanize 0.4.5
xlrd 1.2.0 (using older version because 2.0 dropped .xlsx support)
matplotlib 3.3.3 
Intel Core i5-4570S
8GB RAM

**Comment by lordlouckster** [comment]
[log.txt](https://github.com/dlenski/top500/files/6209775/log.txt)

**Comment by dlenski** [comment]
[See above](https://github.com/dlenski/top500/issues/4#issuecomment-805110239). You should explain step-by-step, what you did, and how to can reproduce it, rather than expect readers to dig through your log files and figure it out themselves.
